# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~>  4.8.2'
  pod 'ReachabilitySwift'
  pod 'R.swift'
  pod 'Kingfisher', '~> 7.0'
  pod 'SkeletonView'
  pod 'SWXMLHash', '~> 5.0.0'
  # Pods for DemoApp

end
